TRUNCATE TABLE MRM.BATCH_JOB_EXECUTION;
TRUNCATE TABLE MRM.BATCH_JOB_EXECUTION_CONTEXT;
TRUNCATE TABLE MRM.BATCH_JOB_EXECUTION_NOTES;
TRUNCATE TABLE MRM.BATCH_JOB_EXECUTION_PARAMS;
TRUNCATE TABLE MRM.BATCH_JOB_INSTANCE;
TRUNCATE TABLE MRM.BATCH_STEP_EXECUTION;
TRUNCATE TABLE MRM.BATCH_STEP_EXECUTION_CONTEXT;